Fetch hook
levante-trek/marvel-catalog pull request #9
Opened 2022-03-28 08:44 UTC by Caront3

2022-03-28 09:28 UTC, EduardoRG requested changes

2022-03-28 09:28 UTC, EduardoRG commented on package.json
> +    "node-env-run": "^4.0.2",
No es necesaria esta librería, verdad? Podríamos desinstalarla?

2022-03-28 09:28 UTC, EduardoRG commented on src/pages/Heroes/Heroes.tsx
> +  const heroeSingleCard = heroes.map((item, index) => (
El naming de esta variable me parece algo confuso. Mientras que heroeSingleCard me parece un único item, esta variable da valor a un array de items (plural).

2022-03-28 09:28 UTC, EduardoRG commented on src/pages/Heroes/Heroes.tsx
> +    console.log(value);
Dejamos el funcionamiento del buscador para una siguiente tarea? O lo atacamos en este mismo?

2022-03-28 11:12 UTC, Caront3 commented on package.json
> +    "node-env-run": "^4.0.2",
Sí, es prescindible.

2022-03-28 11:13 UTC, Caront3 commented on src/pages/Heroes/Heroes.tsx
> +  const heroeSingleCard = heroes.map((item, index) => (
La modificaré en el siguiente paso donde implemento todo en Heroes page

2022-03-28 11:14 UTC, Caront3 commented on src/pages/Heroes/Heroes.tsx
> +    console.log(value);
Así es. En la actual tarea estaba trabajando en la rama de "fetch hook" me parecía razonable realizar el commit aquí y crear una nueva rama "Heroes-Page" en la que trabajar la funcionalidad del buscador e interconectarlo todo finalmente

2022-03-29 07:31 UTC, EduardoRG approved these changes

2022-03-29 07:31 UTC, EduardoRG approved these changes

2022-03-29 07:32 UTC, merged